---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    istio-injection: enabled

---
# Headless service (like PXC StatefulSet service)
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: demo
  labels:
    app: hello
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 8080
    name: http
  selector:
    app: hello

---
# StatefulSet (like PXC) instead of Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
  namespace: demo
spec:
  serviceName: hello
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from $(POD_NAME) in Cluster A!"
        - "-listen=:8080"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
